### ISSUE TITLE
Import category csv store id

### ISSUE THREAD

**Issue by lucav90** [macopedia/CategoryImporter#1]
hi,

i want to import csv categories for specific store id.
Please help me to make modification or developer this features! its more important

regards,
Luca

**Comment by n0kit31** [comment]
Hey @lucav90. Unfortunately at the moment import categories for one specific store id is not possible.
We will add the feature on next release.

**Comment by tmotyl** [comment]
@lucav90 you can also send us PR, we will be happy to review it and merge

**Comment by timbaltissen** [comment]
@tmotyl  Any idea if you will implement this in the near future? Or can you point me to the way we could do this? Thanks!
