### ISSUE TITLE
InstallData::$entityType is deprecated

### ISSUE THREAD

**Issue by oviliz** [macopedia/CategoryImporter#11]
I'm getting the following (Magento 2.4.6 PHP 8.2):
`Deprecated Functionality: Creation of dynamic property Macopedia\CategoryImporter\Setup\InstallData::$entityType is deprecated in vendor/macopedia/magento2-categoryimporter/Setup/InstallData.php on line 29`

Considering the lack of recent commits, I suppose this extensions is abandoned? :(

**Comment by tmotyl** [comment]
its not actively maintained, but we're open to merging PR if you create one.

**Comment by oviliz** [comment]
Hi @tmotyl , I have just raised a PR at https://github.com/macopedia/CategoryImporter/pull/12 to get this working with Magento 2.4.6-p3 and PHP 8.2, if you don't mind reviewing please.

**Comment by idziakjakub** [comment]
Hi @oviliz, your PR is merged to master, thank you for your contribution!
