### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by interequipment** [macopedia/CategoryImporter#3]
How can I install and enable module?

**Comment by thomas-harding** [comment]
- Upload to app/code/Macopedia/CategoryImporter
- Run bin/magento module:enable Macopedia_CategoryImporter in command line

**Comment by n0kit31** [comment]
I've added how to install and enable module into README.md

**Comment by oviliz** [comment]
Hi @n0kit31 , the Readme says to install via "composer or etc." so I've tried the composer way but is not happy.
```
$ composer require macopedia/magento2-categoryimporter
  [InvalidArgumentException]
  Could not find a matching version of package macopedia/magento2-categoryimporter. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```
What am I doing wrong?

Magento 2.3.5p1 | PHP 7.3

**Comment by tmotyl** [comment]
Hi
Please try again, I've just published the extension on packagist https://packagist.org/packages/macopedia/magento2-categoryimporter

**Comment by oviliz** [comment]
Works, thank you very much @tmotyl
