### ISSUE TITLE
Undefined offset: 2 in CategoriesCommand.php

### ISSUE THREAD

**Issue by thomas-harding** [macopedia/CategoryImporter#4]
Hi.

When I run

`bin/magento import:categories -p var/catimport/test.csv`

I get the following error:

`Notice: Undefined offset: 2 in /app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 167`

My CSV looks like:

id;name;parent_id;is_active;is_anchor;include_in_menu;custom_use_parent_settings;description;meta_title;meta_keywords;meta_description

1111;New Category;594;1;0;1;0;;;;

**Comment by henryktews** [comment]
You probably have an empty line at the end of the file

**Comment by henryktews** [comment]
I made fix
#5

**Comment by tmotyl** [comment]
@thomas-harding please try again with current master
