### ISSUE TITLE
expects parameter 2 to be array

### ISSUE THREAD

**Issue by selisc** [macopedia/CategoryImporter#7]
Hi,

I have installed it on Magento 2.2.7 store. 

When I run `bin/magento import:categories -p catalog_product.csv`  then I am getting below error

`Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/mage/app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 159`

My CSV file is having the columns as id, name, parent_id

**Comment by tmotyl** [comment]
@selisc please attach your csv file

**Comment by selisc** [comment]
@tmotyl here is my CSV file. 
[CSV.zip](https://github.com/macopedia/CategoryImporter/files/3121699/CSV.zip)

**Comment by selisc** [comment]
@tmotyl got my CSV file in zip? I can't able to upload my csv directly because of file restriction in Github. So that I have compressed & sent as zip file.

Kindly let me know the file is good enough or I need to modify anything?

Because I am always getting a warning when I import categories.

Thanks.

**Comment by selisc** [comment]
@tmotyl any updates? 

Can you please let me know the exact format of CSV to import categories?

Thanks.

**Comment by n0kit31** [comment]
Hey @selisc! Sorry for delay in update for you issue.

I see that you CSV file has wrong delimiter. As README.md says:
> use semicolon (';') as delimiter in file

Moreover I see that you have associated_skus column in CSV file - please remove it.

One more thing, if you are using parent category in your CSV file, it need to be declared before 2 rows you provided:
> please add parent categories before children in file

**Comment by selisc** [comment]
@n0kit31 Thanks for your reply. 

Can you please upload the proper sample CSV file here?

Thanks.

**Comment by selisc** [comment]
@n0kit31 Again I am facing the issue. Here is my latest CSV with semicolon

**parent_id;id;name
20;342;First
11;545;Test**

What's an issue here?

**Comment by n0kit31** [comment]
@selisc in this case you're missing parent ids row in csv files.

It might look like this to be right:
```
id;name;parent_id
342;First_parent;null
545;Test_parent;null
20;First;342
11;Test;545
```

Hope it helps.

**Comment by selisc** [comment]
Hi @n0kit31  as per your suggestion, I have executed the same but its not working. Here is my updated CSV  :

id;name;parent_id
342;First_parent;null
545;Test_parent;null
1111;First;342
2222;Test;545

Here is the command : bin/magento import:categories -p my.csv

Its showing the error like this : 

`Required header "id" is missing, please fix file `

But I have added "id" in CSV file right. Why its showing like this?

Thanks.

**Comment by n0kit31** [comment]
Hey @selisc. Don't know exact reason why you have this error? Above file works perfectly for me. Did you try to copy source to text editor and save as new csv file?
If that doesn't help try to debug the code and find out why headersMap array doesn't contain id position.

**Comment by selisc** [comment]
@n0kit31 here is my latest CSV file

```
id;name;parent_id;description;url_key;meta_title
111;First;2;Lorem Ipsum is simply dummy text of the printing and typesetting industry.;first;First Meta
112;Second;2;Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.;second;Second Meta
113;Third;2;When an unknown printer took a galley of type and scrambled it to make a type specimen book.;third;Third Meta
114;Fourth;2;It has survived not only five centuries;fourth;Fourth Meta
115;First Child;111;It was popularised in the 1960s with the release of Letraset sheets Lorem Ipsum passages.;first_child;First Child Meta
116;Second Child;112;More recently with desktop publishing software like Aldus PageMaker including.;second_child;Second Child Meta
117;Third Child;113;Lorem Ipsum is simply dummy text of the printing and typesetting industry.;third_child;Third Child Meta
118;Fourth Child;114;Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.;fourth_child;Fourth Child Meta
```

Is there any issues in that?

Am getting this error :

**`Warning: Invalid argument supplied for foreach() in /var/www/html/mage/app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 182`**

**Comment by n0kit31** [comment]
@selisc as I mentioned previously you need to add parent_id row first.
For categories 111, 112, 113, 114 you set "2" as parent_id. But there is no id = 2 in your csv file.
Add it at the very beginning of you file and should be fine or remove "2" from above rows as parent_id.

**Comment by selisc** [comment]
@n0kit31 Yes, if I set as null instead of 2 in parent_id then its working fine.

Is there any way to set Category Image as like url and meta attributes? 

Thanks.

**Comment by n0kit31** [comment]
Not yet @selisc. Provide pull request for that. I'd be happy to test & merge.

**Comment by CallejaMotos** [comment]
hello,
i am trying this module, and I have exactly same issue at the beggining:

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/magento/app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 159

I have perfect .csv, but doesn't work...
thanks
