### ISSUE TITLE
Invalid argument supplied for foreach() in  on magento 2.3

### ISSUE THREAD

**Issue by maurixxxx** [macopedia/CategoryImporter#8]
Invalid argument supplied for foreach() in public_html/magento2/app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 182

**Comment by n0kit31** [comment]
@maurixxxx can you please attach CSV file to be imported?
In README.md you've got an example of correct file. Please make sure it is similar.

**Comment by maurixxxx** [comment]
I used your sample file, it is attached here.

**Comment by n0kit31** [comment]
@maurixxxx what version of Magent 2.3 do you use exactly?

**Comment by maurixxxx** [comment]
Magento 2.3.2

**Comment by maurixxxx** [comment]
I modified the file deleting some value, and now i get this 
Warning: array_key_exists() expects parameter 2 to be array, null given in /home/esposup/public_html/magento2/app/code/Macopedia/CategoryImporter/Console/Command/CategoriesCommand.php on line 159
the  file is attached
[categories-example.txt](https://github.com/macopedia/CategoryImporter/files/3556524/categories-example.txt)

**Comment by n0kit31** [comment]
Hi @maurixxxx 

First of all, please remove quotation marks from headers of your categories-example.txt file
Second, pull newest repo changes of category importer. I've added some minor improvements.

With all above, you import should work as expected.
